[package]
name = "coto"
version = "0.1.0"
authors = ["MetallicSquid <guillame.Macneil@ccoex.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.6"
tokio = "0.2.21"
async-std = "1.6.2"
uuid = "0.8.1"
